/** Public surface of the API + data layer. */
export { ApiClient, ApiError, type ApiClientOptions, type ApiErrorKind } from './client.js';
export { bootstrapToken, parseTokenHash, type ParsedToken } from './token.js';
export type {
  CatalogEntryMeta,
  CatalogFileRow,
  CatalogInstallResponse,
  CatalogRemoveFile,
  CatalogRemoveResponse,
  CatalogResponse,
  Confidence,
  DetectedAgent,
  FileContent,
  InstalledRecord,
  FixKind,
  HealthResponse,
  InstanceSummary,
  InstancesResponse,
  ManifestStats,
  RedactionSpan,
  Report,
  ReportFinding,
  Severity,
  StorageCleanupResponse,
  StorageEntry,
  StorageHome,
  StorageReport,
  SyncResponse,
  SyncStatus,
  SyncTarget,
  WsMessage,
} from './types.js';
