/** Public surface of the API + data layer. */
export { ApiClient, ApiError, type ApiClientOptions, type ApiErrorKind } from './client.js';
export { bootstrapToken, parseTokenHash, type ParsedToken } from './token.js';
export type {
  AchievementCategory,
  AchievementMeta,
  AchievementsPayload,
  DashboardStats,
  HeatmapCell,
  MessageCounts,
  SessionsResponse,
  SessionSummary,
  SessionDetail,
  SessionTagsResponse,
  ReplayBlock,
  ReplayMessage,
  StatsResponse,
  StreakStats,
  XpStats,
  CatalogEntryMeta,
  CatalogFileRow,
  CatalogInstallResponse,
  CatalogRemoveFile,
  CatalogRemoveResponse,
  CatalogResponse,
  Confidence,
  DetectedAgent,
  FileContent,
  InstalledRecord,
  FixKind,
  HealthResponse,
  InstalledPlugin,
  InstalledPluginsResponse,
  InstallPluginResponse,
  InstanceSummary,
  InstancesResponse,
  ManifestStats,
  MarketplacePlugin,
  MarketplaceResponse,
  RedactionSpan,
  Report,
  ReportFinding,
  Severity,
  StorageCleanupResponse,
  StorageEntry,
  StorageHome,
  StorageReport,
  SyncResponse,
  SyncStatus,
  SyncTarget,
  WsMessage,
} from './types.js';
